### ISSUE TITLE
Microsoft Edge doesn't allow closing the options overlay of waterfall panel

### ISSUE THREAD

**Issue by ofadam** [kpreid/shinysdr#139]
On Microsoft Edge, it doesn't look like there's a way to dismiss the "options" overlay on the waterfall panel.

**Comment by kpreid** [comment]
I checked MDN and it reports that [Microsoft Edge does not support the `<details>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). `<details>` is used heavily in ShinySDR's UI, including for the spectrum options, so that would explain why it does not work; many other sections will not be correctly collapsible either.

I doubt I will spend time on reimplementing a standard feature to make it work, but thanks for the report to document the browser issue!
