### ISSUE TITLE
Map zoom very slow

### ISSUE THREAD

**Issue by bitglue** [kpreid/shinysdr#83]
To go from seeing the entire globe to zooming in on Michigan takes me 17 full pushes of the scroll wheel. Maybe it could be faster?

**Comment by kpreid** [comment]
The tradeoff of setting the step size larger is not being able to set the map viewport where you put it, and I was wary of making things too fast because scroll-wheel behavior can vary across platforms. (For example, it takes only five for me.)

On consideration of your feedback and how it feels on my system, I've now multiplied the zoom rate by 10 in e06f23e3b8a768678ee6eecb1a38bc35f63e8ecc. Let me know how it feels.

I also pushed a bug fix that had gotten buried in another project: the map now (again) has numerical lat/long/zoom fields.

**Comment by bitglue** [comment]
Much better, yes. I'm using Google Maps as a point of reference, and it seems the zoom speed is about the same now. Thanks again!

**Comment by bitglue** [comment]
Unrelated, but at least for me the numerical display is truncated in a rather ugly way:

![2017-06-07-102207_178x143_scrot](https://user-images.githubusercontent.com/1232472/26883429-31145372-4b6b-11e7-8c63-229519906bdf.png)

**Comment by kpreid** [comment]
> I'm using Google Maps as a point of reference, and it seems the zoom speed is about the same now.

Google Maps has acceleration, though, so it's not quite directly comparable.

> the numerical display is truncated in a rather ugly way

Yeah, known issue. Need to truncate to a specific number of digits and make sure that this doesn't quantize the actual pan/zoom levels. It's not a priority compared to lots of other stuff.
